Repository coze-dev/coze-go, pull requests merged in 2025-09, with the labels that each got.

#100 Potential fix for code scanning alert no. 3: Workflow does not contain permissions
  .github/workflows/ci.yml
Labels: chore

#101 feat: Update audio_speech.go add loudness_rate parameter
  audio_speech.go
Labels: feature

#104 fix: Fix fileKey assignment logic in file upload utility
  request.go
Labels: bug

#102 feat: Update audio_speech.go add emotion and emotion_scale
  audio_speech.go
Labels: feature
